openapi: 3.1.0
info:
  title: TLS Learning API
  description: |
    学習用の TLS クライアントAPIです。 Cipher Suites, Extensions, KeyShares などを自由に指定して TLS 1.3 ハンドシェイクを実行できます。
  version: 1.0.0
servers:
  - url: 'http://localhost:8080'
paths:
  /tls/handshake:
    post:
      summary: TLS 1.3 ハンドシェイクを実行
      description: 指定した TLS 設定でサーバとハンドシェイクを行い、その結果を返します。ハンドシェイクのみでアプリケーションデータは送信しません。
      tags:
        - TLS
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/HandshakeRequest'
      responses:
        '200':
          description: TLS ハンドシェイク成功時のレスポンス
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HandshakeResponse'
        '400':
          description: リクエストパラメータが不正
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /tls/application:
    post:
      summary: TLS 1.3 アプリケーションデータを送信
      description: 指定した TLS 設定でサーバとハンドシェイクを行い、成功後にアプリケーションデータを送信してレスポンスを返します。
      tags:
        - TLS
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ApplicationRequest'
      responses:
        '200':
          description: TLS アプリケーションデータ送信成功時のレスポンス
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApplicationResponse'
        '400':
          description: リクエストパラメータが不正
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
components:
  schemas:
    HandshakeRequest:
      allOf:
        - $ref: '#/components/schemas/TlsClientParameters'
      type: object
    ApplicationRequest:
      allOf:
        - $ref: '#/components/schemas/TlsClientParameters'
      type: object
    TlsClientParameters:
      type: object
      required:
        - protocol_version
        - server_name
        - client_random
        - cipher_suites
        - supported_groups
        - key_shares
        - signature_algorithms
      properties:
        protocol_version:
          type: string
          description: 使用する TLS バージョン
          example: '0x0304'
        server_name:
          type: string
          description: Server Name Indication (SNI)拡張に設定するホスト名。指定しない場合は'server'の値が使用されます。
          example: www.example.com
        client_random:
          type: string
          description: クライアントの Random 値 (hex)
          example: deadbeefdeadbeef...
        cipher_suites:
          type: array
          description: 使用する Cipher Suite のリスト (16進数文字列)
          items:
            type: string
          example:
            - '0x1301'
            - '0x1302'
            - '0x1303'
        supported_groups:
          type: array
          description: サポートする楕円曲線 (KeyShare Group)
          items:
            type: string
          example:
            - '0x001d'
            - '0x0017'
            - '0x0018'
            - '0x0019'
        key_shares:
          type: array
          description: KeyShare に使うアルゴリズム (楕円曲線名)
          items:
            type: string
          example:
            - '0x001d'
            - '0x0017'
        signature_algorithms:
          type: array
          description: サポートする署名アルゴリズム
          items:
            type: string
          example:
            - '0x0403'
            - '0x0503'
            - '0x0804'
        application_data:
          type: string
          description: 送信するアプリケーションデータ（HTTPプロトコル） 平文
          example: "GET / HTTP/1.1\r\nHost: www.example.com\r\nConnection: close\r\n\r\n"
    HandshakeResponse:
      type: object
      description: TLSハンドシェイク成功時のレスポンス
      required:
        - raw_client_hello
        - raw_server_response
        - raw_server_response_decoded
      properties:
        raw_client_hello:
          type: string
          description: ClientHelloのバイト列 (hexエンコード)
        raw_server_response:
          type: string
          description: ServerHelloを含めたサーバー側の応答のバイト列 (hexエンコード)
        raw_server_response_decoded:
          type: string
          description: ServerHelloを含めたサーバー側の応答のバイト列を復号化したもの
    ApplicationResponse:
      type: object
      required:
        - raw_client_hello
        - raw_server_response
        - raw_server_response_decoded
        - raw_server_application_data_response
        - raw_server_application_data_response_decoded
      properties:
        raw_client_hello:
          type: string
          description: ClientHelloのバイト列 (hexエンコード)
        raw_server_response:
          type: string
          description: ServerHelloを含めたサーバー側の応答のバイト列 (hexエンコード)
        raw_server_response_decoded:
          type: string
          description: ServerHelloを含めたサーバー側の応答のバイト列を復号化したもの
        raw_server_application_data_response:
          type: string
          description: ServerHelloを含めたサーバー側の応答のバイト列 (hexエンコード)
        raw_server_application_data_response_decoded:
          type: string
          description: ServerHelloを含めたサーバー側の応答のバイト列を復号化したもの
    ErrorResponse:
      type: object
      required:
        - message
      properties:
        message:
          type: string
          description: エラーメッセージ
