// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package openapi

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
)

// ApplicationRequest defines model for ApplicationRequest.
type ApplicationRequest struct {
	// CipherSuites 使用する Cipher Suite のリスト (16進数文字列)
	CipherSuites *[]string `json:"cipher_suites,omitempty"`

	// ClientRandom クライアントの Random 値 (hex)
	ClientRandom *string `json:"client_random,omitempty"`

	// KeyShares KeyShare に使う鍵情報
	KeyShares *[]KeyShare `json:"key_shares,omitempty"`

	// Port 接続先ポート
	Port *int `json:"port,omitempty"`

	// Server 接続先ホスト名またはIPアドレス
	Server string `json:"server"`

	// ServerName Server Name Indication (SNI)拡張に設定するホスト名。指定しない場合は'server'の値が使用されます。
	ServerName *string `json:"server_name,omitempty"`

	// SignatureAlgorithms サポートする署名アルゴリズム
	SignatureAlgorithms *[]string `json:"signature_algorithms,omitempty"`

	// SupportedGroups サポートする楕円曲線 (KeyShare Group)
	SupportedGroups *[]string `json:"supported_groups,omitempty"`

	// TlsVersions 使用する TLS バージョン
	TlsVersions *[]string `json:"tls_versions,omitempty"`
}

// ApplicationResponse defines model for ApplicationResponse.
type ApplicationResponse struct {
	// Alert エラーがあればアラートメッセージ
	Alert *string `json:"alert,omitempty"`

	// ApplicationResponse サーバから受信し復号したアプリケーションデータ（Base64エンコード）
	ApplicationResponse *[]byte `json:"application_response,omitempty"`

	// HandshakeSuccess ハンドシェイクが成功したかどうか
	HandshakeSuccess *bool `json:"handshake_success,omitempty"`

	// RawServerResponse サーバから受信した全データ（hex表示）
	RawServerResponse *string `json:"raw_server_response,omitempty"`
}

// ConnectionTarget defines model for ConnectionTarget.
type ConnectionTarget struct {
	// Port 接続先ポート
	Port *int `json:"port,omitempty"`

	// Server 接続先ホスト名またはIPアドレス
	Server string `json:"server"`
}

// HandshakeRequest defines model for HandshakeRequest.
type HandshakeRequest struct {
	// CipherSuites 使用する Cipher Suite のリスト (16進数文字列)
	CipherSuites *[]string `json:"cipher_suites,omitempty"`

	// ClientRandom クライアントの Random 値 (hex)
	ClientRandom *string `json:"client_random,omitempty"`

	// KeyShares KeyShare に使う鍵情報
	KeyShares *[]KeyShare `json:"key_shares,omitempty"`

	// Port 接続先ポート
	Port *int `json:"port,omitempty"`

	// Server 接続先ホスト名またはIPアドレス
	Server string `json:"server"`

	// ServerName Server Name Indication (SNI)拡張に設定するホスト名。指定しない場合は'server'の値が使用されます。
	ServerName *string `json:"server_name,omitempty"`

	// SignatureAlgorithms サポートする署名アルゴリズム
	SignatureAlgorithms *[]string `json:"signature_algorithms,omitempty"`

	// SupportedGroups サポートする楕円曲線 (KeyShare Group)
	SupportedGroups *[]string `json:"supported_groups,omitempty"`

	// TlsVersions 使用する TLS バージョン
	TlsVersions *[]string `json:"tls_versions,omitempty"`
}

// HandshakeResponse defines model for HandshakeResponse.
type HandshakeResponse struct {
	// Alert エラーがあればアラートメッセージ
	Alert *string `json:"alert,omitempty"`

	// HandshakeSuccess ハンドシェイクが成功したかどうか
	HandshakeSuccess *bool `json:"handshake_success,omitempty"`

	// RawClientHello クライアントから送信された ClientHello の生データ（hex 表示）
	RawClientHello *string `json:"raw_client_hello,omitempty"`

	// RawServerResponse サーバからの ServerHello を含む応答データ（hex 表示）
	RawServerResponse *string `json:"raw_server_response,omitempty"`

	// SharedSecret ハンドシェイクで導出された共通鍵（hex 表示）
	SharedSecret *string `json:"shared_secret,omitempty"`
}

// KeyShare defines model for KeyShare.
type KeyShare struct {
	// Data 公開鍵データ（hex 文字列）
	Data *string `json:"data,omitempty"`

	// Group 曲線名
	Group *string `json:"group,omitempty"`
}

// TlsClientParameters defines model for TlsClientParameters.
type TlsClientParameters struct {
	// CipherSuites 使用する Cipher Suite のリスト (16進数文字列)
	CipherSuites *[]string `json:"cipher_suites,omitempty"`

	// ClientRandom クライアントの Random 値 (hex)
	ClientRandom *string `json:"client_random,omitempty"`

	// KeyShares KeyShare に使う鍵情報
	KeyShares *[]KeyShare `json:"key_shares,omitempty"`

	// ServerName Server Name Indication (SNI)拡張に設定するホスト名。指定しない場合は'server'の値が使用されます。
	ServerName *string `json:"server_name,omitempty"`

	// SignatureAlgorithms サポートする署名アルゴリズム
	SignatureAlgorithms *[]string `json:"signature_algorithms,omitempty"`

	// SupportedGroups サポートする楕円曲線 (KeyShare Group)
	SupportedGroups *[]string `json:"supported_groups,omitempty"`

	// TlsVersions 使用する TLS バージョン
	TlsVersions *[]string `json:"tls_versions,omitempty"`
}

// PostTlsApplicationJSONRequestBody defines body for PostTlsApplication for application/json ContentType.
type PostTlsApplicationJSONRequestBody = ApplicationRequest

// PostTlsHandshakeJSONRequestBody defines body for PostTlsHandshake for application/json ContentType.
type PostTlsHandshakeJSONRequestBody = HandshakeRequest

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// PostTlsApplicationWithBody request with any body
	PostTlsApplicationWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostTlsApplication(ctx context.Context, body PostTlsApplicationJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostTlsHandshakeWithBody request with any body
	PostTlsHandshakeWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostTlsHandshake(ctx context.Context, body PostTlsHandshakeJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) PostTlsApplicationWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostTlsApplicationRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostTlsApplication(ctx context.Context, body PostTlsApplicationJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostTlsApplicationRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostTlsHandshakeWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostTlsHandshakeRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostTlsHandshake(ctx context.Context, body PostTlsHandshakeJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostTlsHandshakeRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewPostTlsApplicationRequest calls the generic PostTlsApplication builder with application/json body
func NewPostTlsApplicationRequest(server string, body PostTlsApplicationJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostTlsApplicationRequestWithBody(server, "application/json", bodyReader)
}

// NewPostTlsApplicationRequestWithBody generates requests for PostTlsApplication with any type of body
func NewPostTlsApplicationRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/tls/application")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewPostTlsHandshakeRequest calls the generic PostTlsHandshake builder with application/json body
func NewPostTlsHandshakeRequest(server string, body PostTlsHandshakeJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostTlsHandshakeRequestWithBody(server, "application/json", bodyReader)
}

// NewPostTlsHandshakeRequestWithBody generates requests for PostTlsHandshake with any type of body
func NewPostTlsHandshakeRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/tls/handshake")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// PostTlsApplicationWithBodyWithResponse request with any body
	PostTlsApplicationWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostTlsApplicationResponse, error)

	PostTlsApplicationWithResponse(ctx context.Context, body PostTlsApplicationJSONRequestBody, reqEditors ...RequestEditorFn) (*PostTlsApplicationResponse, error)

	// PostTlsHandshakeWithBodyWithResponse request with any body
	PostTlsHandshakeWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostTlsHandshakeResponse, error)

	PostTlsHandshakeWithResponse(ctx context.Context, body PostTlsHandshakeJSONRequestBody, reqEditors ...RequestEditorFn) (*PostTlsHandshakeResponse, error)
}

type PostTlsApplicationResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *ApplicationResponse
}

// Status returns HTTPResponse.Status
func (r PostTlsApplicationResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostTlsApplicationResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PostTlsHandshakeResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *HandshakeResponse
}

// Status returns HTTPResponse.Status
func (r PostTlsHandshakeResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostTlsHandshakeResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// PostTlsApplicationWithBodyWithResponse request with arbitrary body returning *PostTlsApplicationResponse
func (c *ClientWithResponses) PostTlsApplicationWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostTlsApplicationResponse, error) {
	rsp, err := c.PostTlsApplicationWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostTlsApplicationResponse(rsp)
}

func (c *ClientWithResponses) PostTlsApplicationWithResponse(ctx context.Context, body PostTlsApplicationJSONRequestBody, reqEditors ...RequestEditorFn) (*PostTlsApplicationResponse, error) {
	rsp, err := c.PostTlsApplication(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostTlsApplicationResponse(rsp)
}

// PostTlsHandshakeWithBodyWithResponse request with arbitrary body returning *PostTlsHandshakeResponse
func (c *ClientWithResponses) PostTlsHandshakeWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostTlsHandshakeResponse, error) {
	rsp, err := c.PostTlsHandshakeWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostTlsHandshakeResponse(rsp)
}

func (c *ClientWithResponses) PostTlsHandshakeWithResponse(ctx context.Context, body PostTlsHandshakeJSONRequestBody, reqEditors ...RequestEditorFn) (*PostTlsHandshakeResponse, error) {
	rsp, err := c.PostTlsHandshake(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostTlsHandshakeResponse(rsp)
}

// ParsePostTlsApplicationResponse parses an HTTP response from a PostTlsApplicationWithResponse call
func ParsePostTlsApplicationResponse(rsp *http.Response) (*PostTlsApplicationResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostTlsApplicationResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ApplicationResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParsePostTlsHandshakeResponse parses an HTTP response from a PostTlsHandshakeWithResponse call
func ParsePostTlsHandshakeResponse(rsp *http.Response) (*PostTlsHandshakeResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostTlsHandshakeResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest HandshakeResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// TLS 1.3 アプリケーションデータを送信
	// (POST /tls/application)
	PostTlsApplication(ctx echo.Context) error
	// TLS 1.3 ハンドシェイクを実行
	// (POST /tls/handshake)
	PostTlsHandshake(ctx echo.Context) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// PostTlsApplication converts echo context to params.
func (w *ServerInterfaceWrapper) PostTlsApplication(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostTlsApplication(ctx)
	return err
}

// PostTlsHandshake converts echo context to params.
func (w *ServerInterfaceWrapper) PostTlsHandshake(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostTlsHandshake(ctx)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.POST(baseURL+"/tls/application", wrapper.PostTlsApplication)
	router.POST(baseURL+"/tls/handshake", wrapper.PostTlsHandshake)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/9RXbW8bxxH+K4dtgdgAwRfJElwC/aAojkVEcGlTbgu4BrEiV+TZx7vL7dIWYQjg3kUS",
	"VVGxqsomIieVlToWbUWUX6I6cW3xx6yPFD/lLxS7d6RI3unNhRPkE3l7tzszzzzPzOwdkNJyuqYilWAQ",
	"vQNwKotyUPwd0XVFTkEia+oV9HkeYcJXoaL8aQpEr90BvzfQFIiC34UOTgi520OjmqqiFN86AY0MImAm",
	"cPSGCQWPKjJSSRwaMIcIMjCYuR4AuqHpyCAyEi7BA5eSaUggX0sjnDJkna+BKGisVey7r+zyfUYrjD5u",
	"Fem7+gajXzFzcWxiIs6sDWZZzPwvs94w80dGnzL6hNEaM79lVoVZT5n5XLx6xaxNZr1k1rx4rP/8pvQx",
	"xGj4HDOrfN18ydethZ/fLIAAQNMwpysIRMGV8J+vxkbPZxKfXrl6dfT89PiNC5dGb2ZvpQYvD8fG0oPp",
	"wpCCLn5KUhenlfHcpVuTl8OffXJZ+yMIgCnNyEEComCyQBAIAFLQ+YmYGLKaATMzAWCgz/OygdIges0L",
	"xfXODm3yBkpxyHtTiHVNxYhD1geqggziRVIE+oRHScuMmswsM/pM4CQWrVIfll6PAz1OGl0O9FvaFScu",
	"M7rIzAX7bkXkrGLvPbHvvhKJXP8/E3QMtgGQhWoaZ+FNlMT5VAph7OOmdVcYXODGzU1mPmLmDqPlRmnZ",
	"/vu66yZdFISaY3TxwMykpikIqtyOAW8nMTJuIeM9AGF03Z6tdoecRdP7G9Xmo9dOmF7KeCjhUaaHD7rW",
	"psMUzCsERM+dGwz0y+zL75r/WbNnS8z6xmHDgXVZJSiDDG7MidRHpQfbHzDzJ2aV7OUlRvcEgjuxuMj2",
	"ArO+Z+ZPPfK6fft20H0KprTcsSpxHfDTxlg7479ecTvKp19Brb+kBlICj2QWKYrmF80Od5yf/q2wV3KU",
	"0C7n90R865KD6hg/RGK01lxd7xOHdIQ63k+MjNakhNjjmjVX7OUtZhbt+tfN7dVT2cdZaKB0EqOUgciJ",
	"wd60n31pz7/uoGDPPm8V11pLu8eb9CsIn6FCgvvhpZp/h7Vnv2/dX2wt7faH2rg/b29X7FKlvyemEUxP",
	"IjTV/g0Gg35oZAwtr/vUigcvmq/W7OWlnjP/OjA0FPnDySL0k58n2JSsZ5GRxHmZIB/iv3tbb65WnUFC",
	"GhXfSgn+LeedaEu8iklnIsOt4ovGvWcdMM52u30NhKcjg+EICDh/BnhlkgnKCYseRNwFaBiwwJ9d0RhQ",
	"TWu5k6mmJl0RX0t28ZF0Joumz75Pam6iQlKQ1QeZNn8kRrfeva0zOtda2m1Ys/bD56AruKPqY4eCPjG7",
	"+lRhzkebjhClSzCHpJiadkcN6UziUuxsY3HDfrPL6NZ+dduurTmp6+k3RbNRnhevKmIQ/MJ++IO9XGJ0",
	"5yPH6keM1uziI0bL7fQ7ktvjhxXN03WmAMByRoUkb6AkVDKaIZNsDh9Sb9ym6jjdfPuCu8uTusXMHwTb",
	"XjPrYS+zLox+khj5i0yy8YGh4RE1nRgbGRgaPh3BcF7n3R+lk0KMJ/Ku8d09e27OUal0psOGi/yAPvJ3",
	"RBs/tWdEwclbyMCypuKe4eQamBhPRIKD/LgjJDsxnpB4DXfGfjE6gpPb91YVviSrUz69y95+3KyvCMs1",
	"x6xHliPxGKObDol6igkOSBemCVJFmAGpDSaW3IuKubI//7S5+pzRrS7qPhZmIsFByb9jmCt2bX1/oyxs",
	"LnXo+zeVk1Qmgr78hHEEDVVWM9JIPAYCwIUbREEkGA6GOSqajlSoyyAKBoORYBgEgA5JViAYIgoOdc37",
	"ziSJfdpal+frwvO2QDe7Wm31sFBEHF+wInVGDnuvzOjWsbcDZq60ZwcOmDNZCiK/5H/Mlf36qnh1IG3e",
	"HEQksTSIgriGyYSCuy5UwJk0ESYfa+mCaCGaSpBK+i6qoRvYQcOpdsfVQp9b90zvVEuMPBILzsQi0B8I",
	"hz+MB+5UJFzoTaND7WNwd0B3UtX4yhS9sgd6zqpzjvP9w89TkfCqU6+Z9Q8xym64+aTldz8uNbb/zfcP",
	"+e5vc8mem21Z1c58LMSM87kcNApuFEI5J2YQFw3MYLfygOv8PEH+zvj8wanP6Dd82t1dbvzray93Dxkb",
	"a4zWhaHjAqU7XVLZY/QBM/95hCQ6d5YPJAjPPe0XloP3TnaYGPxw/y1Q/8im4aV7ZyjD4qacNxQQBVlC",
	"9GgopGgpqGQ1TKLnw+fDYOb6zP8CAAD//1Mwsk5hFAAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
