openapi: 3.1.0
info:
  title: TLS Learning API
  description: >
    学習用の TLS クライアントAPIです。
    Cipher Suites, Extensions, KeyShares などを自由に指定して TLS 1.3 ハンドシェイクを実行できます。
  version: 1.0.0
servers:
  - url: http://localhost:8080

paths:
  /tls/handshake:
    $ref: './paths/tls_handshake.yaml'
  /tls/application:
    $ref: './paths/tls_application.yaml'

components:
  schemas:
    HandshakeRequest:
      $ref: './schemas/request.yaml#/HandshakeRequest'
    ApplicationRequest:
      $ref: './schemas/request.yaml#/ApplicationRequest'
    TlsClientParameters:
      $ref: './schemas/request.yaml#/TlsClientParameters'
    HandshakeResponse:
      $ref: './schemas/response.yaml#/HandshakeResponse'
    ApplicationResponse:
      $ref: './schemas/response.yaml#/ApplicationResponse'
    ErrorResponse:
      $ref: './schemas/response.yaml#/ErrorResponse'