openapi: 3.1.0
info:
  title: TLS Learning API
  description: >
    学習用の TLS クライアントAPIです。
    Cipher Suites, Extensions, KeyShares などを自由に指定して TLS 1.3 ハンドシェイクを実行できます。
  version: 1.0.0
servers:
  - url: http://localhost:8080

#============================================================
# Paths: APIエンドポイントの定義
#============================================================
paths:
  /tls/handshake:
    post:
      summary: TLS 1.3 ハンドシェイクを実行
      description: 指定した TLS 設定でサーバとハンドシェイクを行い、その結果を返します。ハンドシェイクのみでアプリケーションデータは送信しません。
      tags:
        - TLS
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/HandshakeRequest'
      responses:
        '200':
          description: TLS ハンドシェイク成功時のレスポンス
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HandshakeResponse'
        '400':
          description: リクエストパラメータが不正
        '500':
          description: サーバ内部エラー

  /tls/application:
    post:
      summary: TLS 1.3 アプリケーションデータを送信
      description: 指定した TLS 設定でサーバとハンドシェイクを行い、成功後にアプリケーションデータを送信してレスポンスを返します。
      tags:
        - TLS
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ApplicationRequest'
      responses:
        '200':
          description: TLS アプリケーションデータ送信成功時のレスポンス
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApplicationResponse'
        '400':
          description: リクエストパラメータが不正
        '500':
          description: サーバ内部エラー

#============================================================
# Components: 再利用可能なスキーマの定義
#============================================================
components:
  schemas:
    #------------------------------------------------------------
    # リクエスト関連のスキーマ
    #------------------------------------------------------------

    # Schema for /tls/handshake endpoint request body
    HandshakeRequest:
      allOf:
        - $ref: '#/components/schemas/ConnectionTarget'
        - $ref: '#/components/schemas/TlsClientParameters'
      type: object

    # Schema for /tls/application endpoint request body
    ApplicationRequest:
      allOf:
        - $ref: '#/components/schemas/ConnectionTarget'
        - $ref: '#/components/schemas/TlsClientParameters'
      type: object
      required:
        - application_data
      properties:
        application_data:
          type: string
          format: byte
          description: 暗号化して送信するHTTPメッセージなどのアプリケーションデータ（Base64エンコード）
          example: "R0VUIC8gSFRUUC8xLjENCkhvc3Q6IHd3dy5leGFtcGxlLmNvbQ0KDQo="

    # Schema for connection target information
    ConnectionTarget:
      type: object
      required:
        - server
      properties:
        server:
          type: string
          description: 接続先ホスト名またはIPアドレス
          example: www.example.com
        port:
          type: integer
          description: 接続先ポート
          default: 443

    # Schema for TLS client parameters
    TlsClientParameters:
      type: object
      properties:
        server_name:
          type: string
          description: Server Name Indication (SNI)拡張に設定するホスト名。指定しない場合は'server'の値が使用されます。
          example: www.example.com
        client_random:
          type: string
          description: クライアントの Random 値 (hex)
          example: "deadbeefdeadbeef..."
        cipher_suites:
          type: array
          description: 使用する Cipher Suite のリスト (16進数文字列)
          items:
            type: string
          example:
            - "0x1301"
            - "0x1302"
        supported_groups:
          type: array
          description: サポートする楕円曲線 (KeyShare Group)
          items:
            type: string
          example:
            - X25519
            - P256
        key_shares:
          type: array
          description: KeyShare に使う鍵情報
          items:
            $ref: '#/components/schemas/KeyShare'
        signature_algorithms:
          type: array
          description: サポートする署名アルゴリズム
          items:
            type: string
          example:
            - ECDSAWithP256AndSHA256
        tls_versions:
          type: array
          description: 使用する TLS バージョン
          items:
            type: string
          default: ["TLS1.3"]

    # Schema for the KeyShare object
    KeyShare:
      type: object
      properties:
        group:
          type: string
          description: 曲線名
          example: X25519
        data:
          type: string
          description: 公開鍵データ（hex 文字列）
          example: "deadbeefdeadbeef..."

    #------------------------------------------------------------
    # レスポンス関連のスキーマ
    #------------------------------------------------------------
    HandshakeResponse:
      type: object
      properties:
        handshake_success:
          type: boolean
          description: ハンドシェイクが成功したかどうか
        raw_client_hello:
          type: string
          description: クライアントから送信された ClientHello の生データ（hex 表示）
        raw_server_response:
          type: string
          description: サーバからの ServerHello を含む応答データ（hex 表示）
        shared_secret:
          type: string
          description: ハンドシェイクで導出された共通鍵（hex 表示）
        alert:
          type: string
          description: エラーがあればアラートメッセージ

    ApplicationResponse:
      type: object
      properties:
        handshake_success:
          type: boolean
          description: ハンドシェイクが成功したかどうか
        application_response:
          type: string
          format: byte
          description: サーバから受信し復号したアプリケーションデータ（Base64エンコード）
        raw_server_response:
          type: string
          description: サーバから受信した全データ（hex表示）
        alert:
          type: string
          description: エラーがあればアラートメッセージ