package crypto

import (
	"bytes"
	"testing"
)

func TestGenerateRandom32Bytes(t *testing.T) {
	randomBytes1, err := GenerateRandom32Bytes()
	if err != nil {
		t.Fatalf("GenerateRandom32Bytes returned an error: %v", err)
	}
	if len(randomBytes1) != 32 {
		t.Fatalf("Expected a 32-byte array, but got %d bytes", len(randomBytes1))
	}

	var allZeros [32]byte
	if bytes.Equal(randomBytes1[:], allZeros[:]) {
		t.Fatal("Generated bytes are all zeros, which is highly unlikely for a random generator.")
	}

	randomBytes2, err := GenerateRandom32Bytes()
	if err != nil {
		t.Fatalf("GenerateRandom32Bytes returned an error on the second call: %v", err)
	}
	if bytes.Equal(randomBytes1[:], randomBytes2[:]) {
		t.Fatal("Two calls to GenerateRandom32Bytes produced the same result, which should not happen.")
	}
}
